nomad-nginx:
  ports:
    - "8000:8000"
  volumes_from:
    - nomad-web
  links:
    - nomad-web

nomad-web:
  restart: "always"
  command: ./bin/web
  expose:
    - "8000"
  environment:
    - NOMADBOARD_DEBUG=0
    - NOMADBOARD_SECRET_KEY  # if not defined, it gets the value from hosts environment

nomad-db:
  restart: "always"
  volumes:
    - /docker/nomad-postgres/data:/var/lib/postgresql/data
    - /docker/logs/nomad-postgresql:/var/log/postgresql

nomad-nginx:
  restart: "always"
  ports:
    - "80:80"
