nomad-web:
  command: django-admin runserver 0.0.0.0:80
  ports:
    - "80:80"
  environment:
    - NOMADBOARD_DEBUG=0
    - NOMADBOARD_DJANGO_SETTINGS_MODULE=nomadboard.settings
    - NOMADBOARD_SECRET_KEY  # if not defined, it gets the value from hosts environment
