nomad-web:
  restart: "always"
  environment:
    - NOMADBOARD_DEBUG=0
    - NOMADBOARD_SECRET_KEY  # if not defined, it gets the value from hosts environment

nomad-db:
  restart: "always"
  volumes:
    - /docker/nomad-postgres/data:/var/lib/postgresql/data
    - /docker/logs/nomad-postgresql:/var/log/postgresql

nomad-nginx:
  restart: "always"
  ports:
    - "80:80"
