nomad-web:
  restart: "always"
  command: django-admin runserver 0.0.0.0:80
  ports:
    - "80:80"
  environment:
    - NOMADBOARD_DEBUG=False
    - NOMADBOARD_SECRET_KEY  # if not defined, it gets the value from hosts environment

nomad-db:
  restart: "always"
  volumes:
    - /docker/nomad-postgres/data:/var/lib/postgresql/data
    - /docker/logs/nomad-postgresql:/var/log/postgresql

nomad-grunt:
  restart: "always"
