nomad-web:
  container_name: nomad-web
  build: .
  volumes:
    - .:/home/nomadboard/code
  command: django-admin runserver 0.0.0.0:8000
  links:
    - nomad-db
  ports:
    - "8000:8000"
  environment:
    - NOMADBOARD_DEBUG=True
    - DJANGO_SETTINGS_MODULE=nomadboard.settings
    - NOMADBOARD_SECRET_KEY=1337+dev+secret+key

nomad-db:
  container_name: nomad-db
  image: postgres
