nomad-nginx:
  container_name: nomad-nginx
  build: ./docker/nginx/
  dockerfile: Dockerfile
  ports:
    - "8000:8000"
  volumes_from:
    - nomad-web
  links:
    - nomad-web

nomad-web:
  container_name: nomad-web
  build: .
  volumes:
    - .:/home/nomadboard/code
  command: ./bin/web
  links:
    - nomad-db
  expose:
    - "8000"
  environment:
    - NOMADBOARD_DEBUG=1
    - DJANGO_SETTINGS_MODULE=nomadboard.settings
    - NOMADBOARD_SECRET_KEY=1337+dev+secret+key
    - PORT=8000

nomad-db:
  container_name: nomad-db
  image: postgres
  environment:
    POSTGRES_PASSWORD: docker
    POSTGRES_USER: docker

nomad-grunt:
  container_name: nomad-grunt
  build: .
  dockerfile: docker/grunt/Dockerfile
  volumes:
    - ./nomadboard/nomadboard/static:/home/nomadboard/code/nomadboard/nomadboard/static
    - ./Gruntfile.js:/home/nomadboard/code/Gruntfile.js
    - ./package.json:/home/nomadboard/code/package.json
    - ./.jshintrc:/home/nomadboard/code/.jshintrc
