# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True),
        ),
    ]
