# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20160113_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.SlugField(max_length=80, unique=True),
        ),
    ]
